1. Try the zero_to_one_qubit function out with different percentages. What do
you get for 100% zero_qubit? For 100% one_qubit?

In [ ]:
[1,0];[0,1]

2. Write a function to go from the qubit back to your original percentages, and call
it qubit_to_percentages.

In [ ]:
#question: I wrote the formula assuming we're in the 0,1 basis. Should it give percentages in
#all basis sets?
def qubit_to_percentages(qubit):
    zero = 100*qubit.item(0)*qubit.item(0)
    one = 100*qubit.item(1)*qubit.item(1)
    return (zero,one)

3. Using the definition of in words/algebra given in the chapter,
rewrite clockwisearrow_qubit to be a sum of zero_qubit and one_qubit.

In [7]:
import numpy as np
zero_qubit=np.matrix('1; 0')
one_qubit=np.matrix('0; 1')
clockwisearrow_qubit=1/np.sqrt(2)*np.matrix([[1],[np.complex(0,1)]])   

clockwisearrow_zero_one = 1/np.sqrt(2)*np.matrix(zero_qubit + np.complex(0,1)*one_qubit)
print(clockwisearrow_qubit == clockwisearrow_zero_one)

[[ True]
 [ True]]


4. Use get_bloch_coordinates to check the coordinates of all the basis qubits we
have learned in this chapter. Verify that they match the diagram.

In [10]:
plus_qubit=1/np.sqrt(2)*np.matrix('1; 1')
minus_qubit=1/np.sqrt(2)*np.matrix('1; -1')
clockwisearrow_qubit=1/np.sqrt(2)*np.matrix([[1],[np.complex(0,1)]])    
counterclockwisearrow_qubit=1/np.sqrt(2)*np.matrix([[1],[-np.complex(0,1)]])
def get_bloch_coordinates(qubit):
    def get_x_bloch(qubit):
        qubit_x_basis=1./np.sqrt(2)*np.matrix('1 1; 1 -1')*qubit 
        prob_zero_qubit=(qubit_x_basis.item(0)*qubit_x_basis.item(0).conjugate()).real
        prob_one_qubit=(qubit_x_basis.item(1)*qubit_x_basis.item(1).conjugate()).real
        return prob_zero_qubit-prob_one_qubit
        
    def get_y_bloch(qubit):
        qubit_y_basis=1./np.sqrt(2)*np.matrix('1 1; 1 -1')*np.matrix([[1,0],[0,-np.complex(0,1)]])*qubit
        prob_zero_qubit=(qubit_y_basis.item(0)*qubit_y_basis.item(0).conjugate()).real
        prob_one_qubit=(qubit_y_basis.item(1)*qubit_y_basis.item(1).conjugate()).real
        return prob_zero_qubit-prob_one_qubit
    
    def get_z_bloch(qubit):
        qubit_z_basis=qubit
        prob_zero_qubit=(qubit_z_basis.item(0)*qubit_z_basis.item(0).conjugate()).real
        prob_one_qubit=(qubit_z_basis.item(1)*qubit_z_basis.item(1).conjugate()).real
        return prob_zero_qubit-prob_one_qubit
    return (get_x_bloch(qubit),get_y_bloch(qubit),get_z_bloch(qubit))

print('|"0"> coordinates are:',get_bloch_coordinates(zero_qubit))
print('|"1"> coordinates are:',get_bloch_coordinates(one_qubit))
print('|"+"> coordinates are:',get_bloch_coordinates(plus_qubit))
print('|"-"> coordinates are:',get_bloch_coordinates(minus_qubit))
print('|"↻"> coordinates are:',get_bloch_coordinates(clockwisearrow_qubit))
print('|"↺"> coordinates are:',get_bloch_coordinates(counterclockwisearrow_qubit))

|"0"> coordinates are: (0.0, 0.0, 1)
|"1"> coordinates are: (0.0, 0.0, -1)
|"+"> coordinates are: (0.9999999999999996, 0.0, 0.0)
|"-"> coordinates are: (-0.9999999999999996, 0.0, 0.0)
|"↻"> coordinates are: (0.0, 0.9999999999999996, 0.0)
|"↺"> coordinates are: (0.0, -0.9999999999999996, 0.0)


5. Use plot_bloch and zero_to_one_qubit to plot a qubit that is 50% |"0"> and
50% |"1">. Notice that you only see one of the four possible options with the
code in this chapter. This is because whenever you take a square root, it could be
either a positive or a negative value (for example, 4 is both 22 and -22 so ).
Our existing functions, zero_to_one_qubit and qubit, only consider the case
where the square roots are both positive values, when in fact there are four
possibilities: positive/positive, positive/negative, negative/positive and
negative/negative. Change the code to take in an argument indicating which of
the possibilities you would like. Now, plot all possible qubits that are
50% |"0"> and 50% |"1"> using your new code.

In [12]:
def zero_to_one_qubit_all(percentage_zero,percentage_one,which):
    if not percentage_zero+percentage_one==100 or percentage_zero<0 or percentage_one<0: raise Exception("percentages must add up to 100\% and both be positive ")
    qu = np.sqrt(percentage_zero/100.)*zero_qubit+np.sqrt(percentage_one/100.)*one_qubit
    if which == 2:
        qu.put(1,qu.item(1)*-1)
    if which == 3:
        qu.put(0,qu.item(0)*-1)
    if which == 4:
        qu = qu * -1
    return qu

def plot_bloch(qubit,color='b',ax=None):
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D
    if not ax:
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')
        
        # draw sphere
        u, v = np.mgrid[0:2*np.pi:20j, 0:np.pi:10j]
        x = np.cos(u)*np.sin(v)
        y = np.sin(u)*np.sin(v)
        z = np.cos(v)
        ax.plot_wireframe(x, y, z, color="k",alpha=.1)
        ax.grid(False)

    coordinates=get_bloch_coordinates(qubit)
    ax.quiver([0],[0],[0],[coordinates[0]],[coordinates[1]],[coordinates[2]],length=1,color=color,arrow_length_ratio=0.3)
    ax.set_xlim([-1,1])
    ax.set_ylim([-1,1])
    ax.set_zlim([-1,1])
    ax.set_xlabel('x: |"-"> to |"+">')
    ax.set_ylabel('y: |"↺"> to |"↻">')
    ax.set_zlabel('z: |"1"> to |"0">')
    ax.view_init(azim=20)
    return ax


for i in range(1,5):
    print(zero_to_one_qubit_all(50,50,i))
    plot_bloch(zero_to_one_qubit_all(50,50,i),color='xkcd:black')
    i = i

[[0.70710678]
 [0.70710678]]
[[ 0.70710678]
 [-0.70710678]]
[[-0.70710678]
 [ 0.70710678]]
[[-0.70710678]
 [-0.70710678]]


6. Write |"counterclockwisearrow_qubit"> and |"clockwisearrow_qubit"> as a superposition between |"+">, |"-"> either in
words/algebra or in code.

In [15]:
clockwise_plus_minus = 1/2*(1+np.complex(0,1))*plus_qubit + 1/2*(1-np.complex(0,1))*minus_qubit
print(clockwise_plus_minus == clockwisearrow_qubit)

counterclockwise_plus_minus = 1/2*(1-np.complex(0,1))*plus_qubit + 1/2*(1+np.complex(0,1))*minus_qubit
print(counterclockwise_plus_minus == counterclockwisearrow_qubit)

[[ True]
 [ True]]
[[ True]
 [ True]]


7. Measuring 1,000 identically prepared |"ten_ninety"> qubits in the |"+"> and |"-
"> basis will return |"+"> approximately what percentage of the time, and |"-
"> what percentage of the time?

In [ ]:
#Assuming these ten_ninety qubits are 10% |"+"> and 90% |"- ">, |"+"> will be returned 10% of the time
# and |"- "> 90% of the time. However if ten_ninety qubits were prepared in the 0/1 basis and measured in the +/-
#basis, they would be 50% |"+"> and 50% |"- ">, since the z axis is orthagonal to the x axis, and thus measuring any qubits
#generated as percentages of 0 and 1 would give this result