Chapter Three Answers

Problem One

In [1]:
%matplotlib inline
import numpy as np
from functools import reduce
from math import log
import itertools

zero_qubit=np.matrix('1; 0')
one_qubit=np.matrix('0; 1')
plus_qubit=1/np.sqrt(2)*np.matrix('1; 1')
minus_qubit=1/np.sqrt(2)*np.matrix('1; -1')
clockwisearrow_qubit=1/np.sqrt(2)*np.matrix([[1],[np.complex(0,1)]])    
counterclockwisearrow_qubit=1/np.sqrt(2)*np.matrix([[1],[-np.complex(0,1)]])

def create_quantum_state(qubits):
    return reduce(lambda x,y:np.kron(x,y),qubits)

register_01=create_quantum_state([zero_qubit,one_qubit])

def get_nqubits_quantum_state(state):
    return int(log(state.size,2))

def measure_in_01_basis(state):
    from random import random
    n_qubits=int(log(state.shape[0],2))
    probabilities=[(coeff*coeff.conjugate()).real for coeff in state.flat]
    rand=random()
    for idx,state_desc in enumerate([''.join(map(str,state_desc)) for state_desc in itertools.product([0, 1], repeat=n_qubits)]):
        if rand < sum(probabilities[0:(idx+1)]):
            return '|"%s">' % state_desc
    
print(measure_in_01_basis(create_quantum_state([one_qubit,zero_qubit,zero_qubit,one_qubit,one_qubit])))

|"10011">


In [2]:
for i in range(10):
    bell_state_phi_plus=(create_quantum_state([zero_qubit,zero_qubit])+create_quantum_state([one_qubit,one_qubit]))/np.sqrt(2)
    print(measure_in_01_basis(bell_state_phi_plus))

|"00">
|"00">
|"00">
|"00">
|"00">
|"11">
|"00">
|"00">
|"00">
|"00">


In [3]:
def get_qubits_from_state(state):
    basis_states=[zero_qubit,one_qubit,plus_qubit,minus_qubit,clockwisearrow_qubit,counterclockwisearrow_qubit]
    for separated_state in itertools.product(basis_states, repeat=get_nqubits_quantum_state(state)):
        candidate_state=create_quantum_state(separated_state)
        if np.allclose(candidate_state,state):
            return separated_state

In [4]:
register_10011=create_quantum_state([one_qubit,zero_qubit,zero_qubit,one_qubit,one_qubit])
get_qubits_from_state(register_01)
get_qubits_from_state(register_10011)

(matrix([[0],
         [1]]), matrix([[1],
         [0]]), matrix([[1],
         [0]]), matrix([[0],
         [1]]), matrix([[0],
         [1]]))

In [12]:
def zero_to_one_qubit(percentage_zero,percentage_one):
     if not percentage_zero+percentage_one==100 or percentage_zero<0 or percentage_one<0: raise Exception("percentages must add up to 100\% and both be positive ")
     return np.sqrt(percentage_zero/100.)*zero_qubit+np.sqrt(percentage_one/100.)*one_qubit

forty_sixty = zero_to_one_qubit(40,60)
sixty_forty = zero_to_one_qubit(60,40)

test_register = create_quantum_state([forty_sixty,sixty_forty])

get_qubits_from_state(test_register) #note how it returns nothing...

Problem Two

In [17]:
def get_qubits_from_state(state):
    basis_states=[zero_qubit,one_qubit,plus_qubit,minus_qubit,clockwisearrow_qubit,counterclockwisearrow_qubit,forty_sixty,sixty_forty]
    for separated_state in itertools.product(basis_states, repeat=get_nqubits_quantum_state(state)):
        candidate_state=create_quantum_state(separated_state)
        if np.allclose(candidate_state,state):
            return separated_state
        
get_qubits_from_state(test_register)

#Finally, an answer.

(matrix([[0.63245553],
         [0.77459667]]), matrix([[0.77459667],
         [0.63245553]]))

Problem Three

T1 = -t / ln(P)

T1 = -10^(-7) / ln(.007)

Problem Four

Quantum Computer B has higher T-values, and hence less decoherence, so it is the better option.

Problem Five

In [51]:
"""def new_measure_in_01_basis(state):
    inp = measure_in_01_basis(state)
    nqub = (len(inp) - 4)
    listof = []
    for i in range(nqub - 2):
        if inp[i+2] == "0":
            listof.append(zero_qubit)
        else:
            listof.append(one_qubit)
    return create_quantum_state(listof)"""

In [50]:
#new_measure_in_01_basis((create_quantum_state([one_qubit,zero_qubit,zero_qubit,one_qubit,one_qubit])))

#This one stumped me, unfortunately. Not sure what I could add to Andrew's answer.

matrix([[0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0]])

Problem Six

In [22]:
def even_newer_measure_in_01_basis(state):
    inp = measure_in_01_basis(state)
    nqub = len(inp) - 4
    listof = []
    for i in range(nqub):
        if inp[i+2] == "0":
            listof.append(zero_qubit)
        else:
            listof.append(one_qubit)
            
        #Here I would somehow refer back to the original input and change it to be == to create_quantum_state(listof)
        #This would change the input state to return the originally-measured value 100% of the time, just like
        #a wave function collapse would. But I can't think of a way to do this without some kind of global variable trick
        
        #I took a look at Andrew's code and he created a class, which looks like a good way to solve this problem.
        #I will leave my attempt here for reference. 

    return measure_in_01_basis(create_quantum_state(listof))
            

In [23]:
new_test_state = create_quantum_state([zero_qubit, plus_qubit, plus_qubit, plus_qubit])

for i in range(10):
    print(measure_in_01_basis(new_test_state))
    
print("New, improved, collapsing measurement:")

for i in range(10):
    print(even_newer_measure_in_01_basis(new_test_state))


|"0001">
|"0100">
|"0110">
|"0100">
|"0100">
|"0000">
|"0110">
|"0110">
|"0000">
|"0100">
New, improved, collapsing measurement:
|"0011">
|"0000">
|"0011">
|"0100">
|"0000">
|"0111">
|"0111">
|"0001">
|"0111">
|"0010">
